const PRODUCT = {
	FETCH: 'PRODUCT_FETCH',
	FETCH_ERROR: 'PRODUCT_FETCH_ERROR',
	FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS'
};

const PRODUCT_LIST = {
	FETCH: 'PRODUCT_LIST_FETCH',
	FETCH_ERROR: 'PRODUCT_LIST_FETCH_ERROR',
	FETCH_SUCCESS: 'PRODUCT_LIST_FETCH_SUCCESS'
}

const PRODUCT_DELETE = {
	DELETE: 'PRODUCT_DELETE',
	DELETE_ERROR: 'PRODUCT_DELETE_ERROR',
	DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS'
}

// const DRAGON = {
// 	FETCH: 'DRAGON_FETCH',
// 	FETCH_ERROR: 'DRAGON_FETCH_ERROR',
// 	FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
// };

export { PRODUCT, PRODUCT_LIST, PRODUCT_DELETE };